#+BEGIN_COMMENT
---
layout: post
title:  "Neo Layout"
father: Computer
---
#+END_COMMENT

Vor zwei Jahren bin ich mehr oder minder über das alternative Tastaturlayout Neo gestolpert und mich seither intensiv mit Ergonomie und der Geschichte des konventionellen QWERTY-Layouts auseinandergesetzt.

* Konventionelles Tastaturlayout
Die heutige übliche Tastaturbelegung geht auf das 19. Jahrhundert zurück. Ziel war, häufige Buchstabenfolgen auf der vormaligen alphabetischen Anordnung der Schreibmaschinentasten möglichst weit auseinanderzulegen, um ein Verkanten der Hämmer zu vermeiden.

Somit wurde auf Grund einer technischen Einschränkung die Tasten explizit so angeordnet, dass sie für den Menschen möglichst schlecht liegen. Diesen technischen Einschränkungen unterliegen wir heutzutage natürlich nicht mehr, jedoch hat sich auf Grund von der bereits etablierten Konvention das bestehende Layout (bis auf regionale Varianten) nicht mehr geändert.

Eine weitere Besonderheit ist, dass man auf der englischen Variante "Typewriter" komplett auf der obersten Reihe schreiben kann, was wohl ein Easteregg ist.

Der horizontale Tastenversatz liegt auch an den Hämmern, die Platz für ihre Traktur benötigten. Jedoch ist dieser Versatz nicht tippfreundlich, da man um höhere oder niedrigere Tasten zu erreichen man seinen Finger nicht nur strecken oder einziehen, sonder auch verdrehen muss.

* Alternative Tastaturlayouts
Mit der Zeit bildeten sich Alternativen heraus, die aber allesamt nicht sehr populär sind, was daran liegen mag, da:
1. Viele kein Zehnfingersystem benutzen
2. QWERTY der ubiquitäre Standard ist
3. Die Nachteile nicht bekannt sind
4. Die alternativen Layouts unbekannt sind

** Dvorak
Das bekannteste und auch älteste Reformlayout ist das Dvorak-Layout, welches 1930 entwickelt wurde. 

*** Ergebnisse
Hierfür wurden verschiedene Studien bezüglich Ergonomie und Effizienz durchgeführt. Wichtige, auch in aktuelleren Reformbelegungen präsente, Ergebnisse waren, dass:
- Die Finger möglichst kurze Bewegungen durchführen sollten
- Dementsprechend sollten möglichst häufige Buchstaben in der Ruheposition der Finger sich befinden
- Der gleiche Finger nicht wiederholt werden sollte
- Im besonderen Maße sollten Sprünge des gleichen Fingers von der obern auf die untere Reihe, oder andersrum vermieden werden
- Dass sich die Hände im optimalfall abwechseln
- Bigramme, also häufige Buchstabenkombinationen, sollten weit entfernt liegen
- Die Hände sollten ungefähr gleich viel zu tun haben
- Die starken Finger sollten häufiger verwendet werden als die schwachen, um Ermüdungserscheinungen zu vermeiden

*** Umsetzung
Diese Ergebnisse konnten jedoch nur händisch umgesetzt werden, da entsprechende Computer zur Berechnung und Optimierung nicht zur Verfügung standen.

Nichts desto trotz wurde eine auch heute noch beliebte und ergonomische Tastaturbelegung erstellt, die in modernen Betriebssystemen als Standard einstellbar ist.

** Ristome
** Neo
Diese Layout wurde 2004 entwickelt und speziell auf die deutsche Sprache optimiert. Die Ergebnisse Dvoraks wurden hier verwendet, um computergestützt das Layout zu optimieren. Jedoch waren die Optimierungsmöglichkeiten selbst noch nicht ausgereift, was zu der Entstehung von Neo2 führte.

*** Neo2
Hier wurde das gesamte Layout nochmals computergestützt deutlich verbessert, so werden die Finger viel weniger bewegt. Beispielsweise kann man 60% eines normalen deutschen Textes auf der Grundreihe tippen.

Eine phantastische Besonderheit des Neolayouts, welche mich damals dazu bewog, es zu lernen, ist, dass es noch zusätzliche Ebenen besitzt. Dies bedeutet, dass man über Spezialtasten die Belegung des Layouts ändern kann (wie z.B. bei Shift, welches für Großbuchstaben sorgt). So gibt es eine Ebene mit einem Zahlen- und Navigationsblock, welche unglaublich praktisch ist. So kann ich, während ich diesen Text hier schreibe, in der Grundposition ohne Probleme Zahlen eingeben, zum letzten Wortanfang springen, zum Zeilenanfang springen, in beide Richtungen Zeichen-, Wort-, Absatz- oder sogar Dokumentenweise löschen. Eine andere Ebene beinhaltet typische Programmierzeichen, eine weitere enthält griechische Buchstaben (für Formeln) und die letzte enthält mathematisch Spezialzeichen (Summationszeichen etc.). 

*** AdNW
Dieses Layout steht für „Aus der Neo-Welt“ und sieht sich selbst als Nachfolger des Neo-Layoutes. Hier wurde das Layout noch weiter verfeinert und nicht nur an deutschen, sondern auch an englischen Texten ausgerichtet. Somit ist dieses Layout weit internationaler und trotzdem auch in der deutschen Sprache dem Neo-Layout deutlich überlegen.

Meines Wissens nach ist dies derzeit das beste und vielseitigste Tastaturlayout. Es wurde von vielen auch schon unter dem Namen Neo3 vorgeschlagen, jedoch gibt es manch eine Unstimmigkeit zwischen den Projekten. Parallel dazu wird an einem anderen Neo3 gearbeitet, was sehr gut ist, da Neo bereits einen beachtlichen Bekanntheitsgrad erlangt hat, so ist das Neo-Layout in jeder Linuxdistro als Belegungsvariante des Deutschen auswählbar.



