
#+BEGIN_COMMENT
---
layout: post
title: Linuxdistributionen
father: Linux
---
#+END_COMMENT


Als ich vor ungefähr 2 Jahren auf Linux umgestiegen bin, stellte ich mir die Frage welche Distribution ich nehmen sollte. Überwältigt von der Vielfalt und zunächst nicht im Stande Desktopumgebungen (Xcfe, Lxde, Gnome …) von Distributionen zu unterscheiden entschied ich mich für Ubuntu.

Nach einer Eingewöhnungszeit wurde mir klar, dass Cannonical (die Firma hinter Ubuntu) Interessen hatte, die mit den meinigen unvereinbar waren. So wechselte ich zu Debian und stellte nach kurzer Zeit die Repository auf Testing. Hier hatte ich mich nun auch an verschiedene Desktopumgebungen rangemacht.

* Distributionen
Distributionen kann man durch mehrere Elemente charakterisieren:

- Packetmanager :: Sie sind für Update- und Installationsprozesse verantwortlich. 
- Desktopumgebung :: Diese stellt eine grafische Oberfläche und verschiedene Standardprogramme bereit, da diese besonders wichtig für die Usability sind, wird hier auch noch detailiert darauf eingegangen. 
- Free vs. Nonfree :: Manche Distributionen enthalten (fast) nur freie Software (z.B. Debian) was zur Konsequenz hat, dass diese von Haus aus die meisten Videocodecs nicht unterstützen. Andere Distribution sind komfortabler (z.B. Mint), da sie alles Notwendige enthalten, um beispielsweise eine DVD oder Youtube-Videos zu sehen. 
- Zielgruppe :: Hier gibt es große Unterschiede, vor allem Ubuntu wird immer Anfängern empfohlen, da vieles ohne Konfiguration funktioniert und technisches unter grafischen Elementen versteckt wird. Arch hingegen hat vor allem erfahrene Nutzer im Blick. Auf ein grafisches Verstecken wird bewusst verzichtet, um maximal präzise Konfiguartionen zu ermöglichen. Erfahrene Nutzer können terminalbasiert schneller arbeiten, ferner wird die CPU durch die fehlenden Extravaganzen geschont. 
- Entwicklungsstrategie :: Hier wird zwischen Rolling- und Nonrolling-release unterschieden. Da dieses Thema für mich besonders interessant ist, wird im Folgenden darauf genauer eingegangen. 

** Nonrolling-release
Die meiste Software hat eine Nonrolling-release-Entwicklung. Sprich es werden stabile Versionen eines Programmes publiziert, von denen man dann Updates zur nächsten stabilen Version machen kann. Bei mancher Software, wie z.B. bei vielen Distributionen ist hierfür eine Neuinstallation notwendig.

*** Debian
Debian ist eine sehr alte Distribution mit sehr vielen Entwicklern. Der Entwicklungsprozess ist sehr konservativ; es werden ungefähr alle zwei Jahre neue Versionen publiziert, welche in der gesamten Zwischenzeit keinen neuen Features, sondern nur Sicherheitsupdates bekommen. Da diese Versionen außerordentlich stabil sind werden diese meist für Server verwendet.

**** Repositorys
Die Repositorys von Debian sind weiterhin in Experimental, Unstable und Testing unterteilt.

***** Experimental
Hier befinden sich Programme, die große Systemveränderungen benötigen oder noch sehr unstabil laufen. Experimental ist kein vollständiges Repository, sondern kann nur zusammen mit Unstable verwendet werden. Generell sollte man dieses Repository meiden, außer man möchte explizit bei der Debianentwicklung mitarbeiten.

***** Unstable
Unstable ist ein vollständiges Repository, welches verwendet werden kann um sehr aktuelle Software zu installieren. Unstable ist ein Rolling-release, Neuinstallationen sind also nurnoch notwendig, falls einem die unstabile Software zu viele Probleme bereitet. Auch von diesem Repository wird i.d.R. abgeraten.

***** Testing
Dieses Repository hat schon eine gewisse Stabilität erreicht, da hier nur Software gelagert wird, die eine Zeit lang ohne Probleme in Unstable war. Jedoch benutzt Testing kein volles Rolling-release-Modell mehr, da immer ein halbes Jahr vor einer neuen stabilen Debianversion es einen Featuerfreeze gibt, in dem die Entwickler sich auf Fehlerbehandlung fokussieren.

**** Derivate
Wegen des Alters und der Größe von Debian entstanden Derivate, also Modifikationen, welche sich vor allem im Bezug zur freien Software unterscheiden.

***** Ubuntu
Die bekannteste Linuxdistro nennt sich Ubuntu, was so viel wie Menschlichkeit bedeutet. Sie ist auf einfache Benutzung und somit auf unerfahrene Benutzer hin optimiert.

****** Kritik
******* Kommerz
In der letzten Zeit wurde Ubuntu immer mehr kommerzialisiert. Auch wenn die Benutzung weiterhin kostenlos ist, so werden nun Verhalten der Benutzer protokolliert und an Amazon verkauft. Ferner strebt die Distribution gewisse Inkompatibilitäten an, welche zu einer Monopolstellung (vor allem auf dem Smartphone-Markt) führen sollen.

******* Stabilität
Weiterhin baut Ubuntu auf dem Unstable-release von Debian auf, ohne jedoch selbst ein Rolling-release zu sein. Dies hat zur Konsequenz, dass zwar aktuelle Software verwendet wird, jedoch diese aber nicht neu gehalten wird, was aber gerade bei unstabiler Software besonders wichtig ist. 

***** Mint
Diese Distro ist ein Fork von Ubuntu. Sie hat auch eher unerfahrene Benutzer im Blick, lässt jedoch mehr Freiheiten und Konfigurierbarkeiten. Zudem setzt mint auf einen klassischen Desktop, im Gegensatz zu Ubuntu.

****** Kritik
******* Codebase
Problematisch dürfte die Basis Ubuntu sein, da dieses immer inkompatibler wird. Somit dürften die Modifikationen, die Mint vornimmt immer schwieriger und monolithischer werden, was den UNIX-Prinzipien widerspricht. Um dem entgegenzutreten wurde eine Version von Mint erstellt, welche direkt auf Debian aufbaut ([[Mint LMDE][LMDE]]).

******* Unfrei
Ferner wird kritisiert, dass Mint standardmäßig eine Vielzahl an unfreier Software installiert (was andererseits zu einer komfortablen Nutzungserfahrung führt).

*** Fedora
Diese Distribution unterscheidet sich in mancherlei Hinsicht von Debian. Sie hat einen anderen Packetmanager, ist (immer) modern und hat eine große Firma im Rücken (Red Hat).

*** OpenSuse
Eine deutsche, weitverbreitete Distro, welche das freie Pendant zu Suse darstellt. Sie hat also auch eine Firma im Rücken (welche unliebsamen Einfluss nehmen kann).

** Rolling-release
Bei Rolling-release-software hat der Anwender stets eine aktuelle Version der Software und kann jederzeit auf den derzeitigen Entwicklungsstand updaten. In aller Regel geschieht dies ohne Neuinstallation. Da es hier aber keine klar definierten Versionen gibt, sondern nur Snapshots, sind evtl. auch mehr Fehler oder Probleme zu finden. Dementsprechend sind die meisten Rolling-release-distributionen für erfahrene Nutzer konzipiert.

*** Arch
[[http://archlinux.org][Arch]] ist eine sehr berühmte Rolling-releas-distro, welche sich vor allem an sehr erfahrene Nutzer wendet. Beispielsweise installiert der Installer (welcher rein Terminalbasiert ist) nur ein minimales System. Eine Desktopumgebung, Videocodecs und Büroprogramme etc. muss selbst installiert werden. Dies hat den unschlagbaren Vorteil, dass nur das installiert wird, was man auch wirklich möchte. Andererseits werden unerfahrene Benutzer mit einem nicht funktionsfähigen System konfrontiert. Um im selbstversuch zu lernen, werde ich vermutlich als nächstes Arch installieren.

**** Aktualität
Eines der Hauptziele von Arch ist es, möglichst nahe der bleeding Edge zu sein. Dies hat den Vorzug stets aktuelle Software zu besitzen und nie wieder das System neu installieren zu müssen, jedoch auch den Nachteil, dass das ganze System hin und wieder unstabil oder gar defekt sein kann. Da die Community sehr aktiv ist, werden Fehler schnell behoben; dennoch empfiehlt sich diese Distro nicht für Server oder sensible Daten.

**** Manjaro
Hier werden versucht, die Vorzüge von Arch mit denen von Mint zu kombinieren, dementsprechend nutzt auch Manjaro standardmäßig die von Mint entwickelte klassische Desktopumgebung Cinnamon. Ferner sind Videocodecs etc. bereits installiert. Leider büßt diese Distro an Aktualität ein, da sie trotz der Codebase Updatepackages verteilt und somit kein volles Rolling-release mehr ist.

*** Debian
Da Debian zwei Repositories hat, die ständig entwickelt werden, kann Debian unter Verwendung dieser auch als Rolling-release-distribution betrachtet werden. Da dies aber nicht der eigentlich konservativen Philosophie Debians entspricht gibt es einige Forks, die auf diesen Repositories aufbauen, nicht aber auf dieser Philosophie.

**** Derivate
***** Aptosid
Eine auf dem Unstable-repository aufbauende Distro.

***** Crunchbang
Ebenso auf Unstable bauend.

***** Mint LMDE
Auf Testing aufbauend, mit der Behauptung (oder Traum), ein Rolling-release zu sein. Da aber das DE viele Probleme bereitet, vertreibt Mint Updatepackages. Trotz dass die Idee eines debianbasierten hervorragend ist, so ist doch die Umsetzung viel schlechter als bei dem originalen Mint.
 
* Desktopumgebungen
Ein Betriebssystem besteht auf den ersten Blick vor allem aus Programmen und einer grafischen Oberfläche (GUI). Diese Elemente sind aber nicht eigentlicher Teil eines Linuxbetriebssystemes, sondern Teil von Desktopumgebungen. Hier sieht man einen grundlegenden Unterschied zwischen Linux und Windows besonders deutlich: Linux ist modular, und nicht monolithisch.

** LXde
Eine besonders ressourcenschonende Desktopumgebung, die vor allem für ältere Rechner gedacht ist. Kritikpunkte sind die alte Software und das sehr kleine Entwicklerteam, was ein verwaisen der Software ermöglicht.

** Xfce
Auch ressourcenschonend, jedoch weiter verbreitet, moderner und mit größerem Entwicklungsteam.

** Kde
Sehr verbreitet, großes Entwicklerteam, grafisch aufwendig und dementsprechend langsam.

** Gnome
Diese DE hat eine lange Entwicklungsgeschichte hinter sich und ist bei vielen Distros der Standard. Jedoch löste das Gnome-Projekt auch eine sehr große Kontroverse mit Gnome3 aus, welches sich vom damaligen klassischen Desktopparadigma (und somit von vielen Nutzern) abwandte.

*** Mate
Ein Fork von Gnome2, welcher versucht, den alten Desktop zu pflegen und mit Sicherheitsaktualisierungen zu versorgen.

*** Cinnamon
Ein Fork von Gnome3, welcher versucht, trotz Integration neuster Softwaretechnologie immernoch eine klassische DE bereitzustellen. Cinnamon ist die Standard-DE von Mint und von Manjaro und erfreut sich großer Beliebtheit.

*** Unity
Ebenso ein Gnome-fork, welcher aber mit dem Original nurnoch sehr wenig zu tun hat. Unity ist mit nahezu allen Distros außer Ubuntu inkompatibel. Es strebt einen primitiven (leicht benutzbaren) Desktop an, der gut auch auf Touch-screens und Tablets verwendet werden kann.
