#+BEGIN_HTML
---
layout: post
title:  "Welcome to Jeiiahikyll!"
date: 2000-11-11
categories: jekyll update
---
#+END_HTML

* Erstes
You'll find this post in your `_posts` directory - edit this post and re-build (or run with the `-w` switch) to see your changes!
To add new posts, simply add a file in the `_posts` directory that follows the convention: YYYY-MM-DD-name-of-post.ext.
** unter
ientr 
- iea
- iea
- ia
1. iea
2. iean

** iaia

ieai
*** ieansrt
hint iant
* ie 
ioatn
** iant
hhh
* iae 
Jekyll lso offers powerful support for code snippets:

{% highlight ruby %}
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
{% endhighlight %}

bla

#+BEGIN_html

{% highlight ruby %}
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
{% endhighlight %}

#+END_html
ia
iea

#+BEGIN_SRC ruby 
def print_hi(name)
puts "Hi, #{name}"    (ref:blubber)
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
#+END_SRC



Check [[(blubber)]] out the [Jekyll docs][jekyll] for more info on how to get the most out of Jekyll. [[(blubber)][File]] all bugs/feature requests at [Jekyll's GitHub repo][jekyll-gh].

[jekyll-gh]: https://github.com/mojombo/jekyll
[jekyll]:    http://jekyllrb.com
